version: '3.4'

services:
  surveys.postgres:
    container_name: surveys_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: surveySystem
      POSTGRES_PASSWORD: surveySystem
      POSTGRES_DB: "surveySystemDB"
    volumes:
      - postgres_dev_data:/var/lib/postgresqldev/data 
    expose:
      - "5438"
    ports:
      - "5438:5432"


volumes:
  postgres_dev_data: