version: '3.4'

services:

  survey_system.api:
    image: ${DOCKER_REGISTRY-}surveysystem_api
    build:
      context: .
      dockerfile: src/Web/SurveySystem.Web/Dockerfile
    container_name: survey_system.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnectionString=User ID=surveySystem;Password=surveySystem;Host=survey_system_postgres;Port=5432;Database=surveySystemDB;Pooling=true;
    depends_on:
      - survey_system.postgres
    ports:
      - "8001:80"

  survey_system.postgres:
    container_name: survey_system_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: surveySystem
      POSTGRES_PASSWORD: surveySystem
      POSTGRES_DB: "surveySystemDB"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    expose:
      - "5437"
    ports:
      - "5437:5432"


volumes:
  postgres_data: