version: '3.4'

services:

  surveySystem.api:
    image: ${DOCKER_REGISTRY-}surveySystem_api
    build:
      context: .
      dockerfile: src/Web/SurveySystem.Web/Dockerfile
    container_name: surveySystem.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnectionString=User ID=surveySystem;Password=surveySystem;Host=surveySystem_postgres;Port=5438;Database=surveySystemDB;Pooling=true;
      - S3__ServiceUrl=http://portfolio_minio:9000
    depends_on:
      - surveySystem.postgres
    ports:
      - "8001:80"

  surveySystem.postgres:
    container_name: surveySystem_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: surveySystem
      POSTGRES_PASSWORD: surveySystem
      POSTGRES_DB: "surveySystemDB"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    expose:
      - "5438"
    ports:
      - "5438:5432"


volumes:
  postgres_data: